services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: matchme
      POSTGRES_PASSWORD: matchme
      POSTGRES_DB: matchme
    ports:
      - "5432:5432"
    volumes:
      - matchme_pg:/var/lib/postgresql/data

volumes:
  matchme_pg:
